name: "Node.js Vulnerabilities"

on: 
  schedule:
    - cron: "0 0 * * *"  # Läuft täglich um Mitternacht
  push:
    branches:
      - main  # Läuft auch bei einem Push zur main-Branch
  pull_request:
    branches:
      - main  # Überprüft ebenfalls bei PRs zur main-Branch

jobs:
  is-my-node-vulnerable:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Check Node.js Vulnerabilities
        uses: nodejs/is-my-node-vulnerable@v1
        with:
          node-version: "lts/*"